theme = "catppuccin_macchiato"

[editor]
true-color = true
bufferline = "always"
text-width = 100
mouse = false
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal.space]
"f" = "file_picker_in_current_directory"
"F" = "file_picker"

[keys.normal]
"C-[" = "jump_backward"
"C-]" = "jump_forward"
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.insert]
"A-x" = "normal_mode"
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"

[keys.select]
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"

