[preset.standard]
create_options = ["-it",
   "-v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK",
   "-e SSH_AUTH_SOCK=$SSH_AUTH_SOCK",
   "-v /dev:/dev",
   "--privileged",
]
cp_cmds = ["/home/archie/dotfiles/bundler/bundle/.  CONTAINER:/tmp/bundle"]
exec_cmds = ["bash -c 'cd /tmp/bundle && bash install.sh'"]
entry_options = ["-it", "-e EDITOR=hx"]
entry_cmd = "/bin/bash"

[environment.std]
devcontainer_json = "$PWD/.devcontainer/devcontainer.json"
presets = ["standard"]

[environment.jump]
image = "quay.io/jumpstarter-dev/jumpstarter:latest"
create_options = ["-v $PWD:/workspace/jumpstarter-testing",]
presets = ["standard"]
