[environment.notus]
dockerfile = "notus-ext.dockerfile"
create_options = ["-v $HOME/.config/helix:/home/user/.config/helix",
   "-v $HOME/Notus:/home/user/west-workspace/notus",
   "-v $HOME/.ssh:/home/user/.ssh",
   "-it",
]
entry_options = ["-it"]
entry_cmd = "/bin/bash"


[environment.notus2]
image = "notusraw"
create_options = ["-v $HOME/dotfiles/helix/.config/helix:/home/user/.config/helix",
   "-v $HOME/notus-workspace/notus:/home/user/west-workspace/notus",
   "-v $HOME/.ssh:/home/user/.ssh",
   "-it",
]
cp_cmds = ["home CONTAINER:/home/user"]
exec_options = ["-u user","-e USER=user"]
exec_cmds = ["bash -c 'cd /home/user/home && ./install.sh'"]
entry_options = ["-it", "-u user", "-e USER=user"]
entry_cmd = "/bin/bash"


[environment.thermal]
image = "thermal"
create_options = ["-v $HOME/arribada/op-thermal-camera:/workspace/op-thermal-camera",
   "-it",
]
entry_options = ["-it"]
entry_cmd = "/bin/bash"
